### ISSUE TITLE
Dekorate 3.x

### ISSUE THREAD

**Issue by iocanel** [dekorateio/dekorate#1029]
We should start working against dekorate 3.x that will use the updated kubernetes-client 6.0.0 model.

### Updated model
- [x] Upgrade kubernetes-client to 6.0.0
- [ ] Leverage new Visitor features

### GitOps friendliness
- [ ] Idempotent manifests by default.
- [ ] Consider moving generated files into the module root instead of the target.

### Module renaming
- [ ] Consider renaming `xxx-annotations` to `dekorate-xxx`.

**Comment by Sgitario** [comment]
I also have some ideas:
- Execution options: allow to dekorate a project without having Dekorate into the runtime dependencies via a command line tool.
- Reduce the number of transitive dependencies that do not add much value (like fusesource jansi)

Consider adding these items into the description if you like the ideas.

**Comment by iocanel** [comment]
https://github.com/dekorateio/dekorate-cli

**Comment by Sgitario** [comment]
> https://github.com/dekorateio/dekorate-cli

If there is an existing tool already, I think we should promote it and update it with the latest extensions. Moreover, we should release the tool into https://www.jbang.dev/appstore/ and add instructions in Dekorate about how to use it.

**Comment by iocanel** [comment]
This was more like a poc rather than something we can promote. 
The original goal of the poc was to check if we can support alternative runtimes.
While, it is possible, I didn't see much interest in it from non-java folks.
