### ISSUE TITLE
Dekorate 2.x

### ISSUE THREAD

**Issue by iocanel** [dekorateio/dekorate#525]
As we have a couple of refactoring going on (_required for the cli_), it should be a good idea to prepare for a major release bump. 

So, I' created a new branch: https://github.com/dekorateio/dekorate/tree/2.0.x

The scope of 2.0.0 currently is:
- [x] Unshade source code #516
- [x] Split logic from annotations & processors #519 
- [x] Remove obsolete modules #526 #527
- [x] Document branches #549
