### ISSUE TITLE
Add ServiceBinding support

### ISSUE THREAD

**Issue by iocanel** [dekorateio/dekorate#675]
- [x] Create a model for ServiceBinding
- [x] Create a ServiceBinding annotation (that will be used to generate the ServiceBindingConfig + Adapters)
  We will need to provide properties like:
  - list of services to binding
  - binding type (via volumes or env vars)
- [x] Create a java annotation processor for ServiceBinding
- [x] Create a generator for ServiceBinding (is meant to populate ServiceBindingConfig)
- [x] Create a handler that reads ServiceBindingConfig and adds the ServiceBinding resource + decorators.

This module will create:
- ServiceBinding

but will also decorate:

- The deployment/deployment config with the mount of the binding secret.
- The deployment/deployment config with env vars (if binding type is env var).

**Comment by yharish991** [comment]
Added a draft version and an example in here https://github.com/yharish991/dekorate/tree/master . ServiceBindingOperator API has changed significantly in the last month, I still need to add those new parameters to completely support ServiceBinding CR

**Comment by yharish991** [comment]
pull request got merged and a release was made https://github.com/dekorateio/dekorate/releases/tag/0.15.0
